actually use the name logstream-cep

diff --git a/smf/logstream-cep b/smf/logstream-cep
--- a/smf/logstream-cep
+++ b/smf/logstream-cep
@@ -1,32 +1,32 @@
 #!/bin/sh
 case "$1" in
   start)
-        echo "Starting CEP"
-        if [ -e "/opt/circonus/var/logstream-cep/cep.pid" ]; then
-            echo "CEP already running with PID " `cat /opt/circonus/var/logstream-cep/cep.pid`
+        echo "Starting logstream-cep"
+        if [ -e "/opt/circonus/var/logstream-cep/logstream-cep.pid" ]; then
+            echo "logstream-cep already running with PID " `cat /opt/circonus/var/logstream-cep/logstream-cep.pid`
         else
-            /opt/circonus/bin/logstream-cep -P /opt/circonus/var/logstream-cep/cep.pid
+            /opt/circonus/bin/logstream-cep -P /opt/circonus/var/logstream-cep/logstream-cep.pid
         fi
         ;; 
   stop) 
-        echo "Stopping CEP"
-        cat /opt/circonus/var/logstream-cep/cep.pid | xargs kill
+        echo "Stopping logstream-cep"
+        cat /opt/circonus/var/logstream-cep/logstream-cep.pid | xargs kill
         if [ 0 = $? ]; then
-            rm /opt/circonus/var/logstream-cep/cep.pid
+            rm /opt/circonus/var/logstream-cep/logstream-cep.pid
         else
-            echo "Error stopping CEP"
+            echo "Error stopping logstream-cep"
         fi
         ;; 
   restart) 
-        echo "Restarting CEP"
-        cat /opt/circonus/var/logstream-cep/cep.pid | xargs kill
+        echo "Restarting logstream-cep"
+        cat /opt/circonus/var/logstream-cep/logstream-cep.pid | xargs kill
         if [ 0 = $? ]; then
-            rm /opt/circonus/var/logstream-cep/cep.pid
-            /opt/circonus/bin/logstream-cep -P /opt/circonus/var/logstream-cep/cep.pid
+            rm /opt/circonus/var/logstream-cep/logstream-cep.pid
+            /opt/circonus/bin/logstream-cep -P /opt/circonus/var/logstream-cep/logstream-cep.pid
         fi
         ;; 
   *) 
-        echo "Usage: cep {start|stop|restart}" >&2 
+        echo "Usage: logstream-cep {start|stop|restart}" >&2 
         exit 3 
         ;; 
 esac
